name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch and process JSON
        run: |
          curl -s https://petition.parliament.uk/petitions/700143.json | jq '.data.attributes.signatures_by_constituency | sort_by(.signature_count) | reverse' > constituencies.json
      - name: Update README
        run: |
          echo "# Constituencies by Signatures" > README.md
          echo "Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> README.md
          echo "" >> README.md
          echo "\`\`\`json" >> README.md
          cat constituencies.json
