name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

permissions:
  contents: write  # Allow the workflow to write to the repository

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and process JSON
        run: |
          # Fetch petition data and extract attributes
          curl -s https://petition.parliament.uk/petitions/700143.json | \
          jq '.data.attributes' > petition_data.json

      - name: Calculate total signatures and update README
        run: |
          # Extract petition details
          PETITION_NAME=$(jq -r '.title' petition_data.json)
          PETITION_URL="https://petition.parliament.uk/petitions/700143"

          # Calculate total signatures by summing the signature_count from each constituency
          TOTAL_SIGNATURES=$(jq '[.signatures_by_constituency[].signature_count] | add' petition_data.json)

          # Get current UTC time for last updated
          LAST_UPDATED=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

          # Write to README.md
          echo "# $PETITION_NAME" > README.md
          echo "URL: [$PETITION_URL]($PETITION_URL)" >> README.md
          echo "Total Signatures: $TOTAL_SIGNATURES" >> README.md
          echo "Last Updated: $LAST_UPDATED" >> README.md
          echo "" >> README.md
          echo "| Constituency | MP | Signatures |" >> README.md
          echo "|--------------|----|-----------:|" >> README.md

          # Append constituency data to README.md
          jq -r '.signatures_by_constituency[] | "| \(.name) | \(.mp) | \(.signature_count) |"' petition_data.json >> README.md

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Update README with latest petition data" || echo "No changes to commit"
          git push
